version: '3'

services:
  postgresWriter:
    image: postgres:latest
    container_name: postgresDBWriter
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: postgresDBWriter
    ports:
      - "5432:5432"
    restart: always
    networks: 
      - remessaNetwork

  remessaAPI:
    build: "./remessaAPI"
    container_name: remessaAPI
    depends_on: 
      - postgresWriter
    networks:
      - remessaNetwork
    environment:
      - PORT=8080
      - API_SECRET=SECRET
      - DB_HOST=postgresDB
      - DB_NAME=postgres
      - DB_USER=admin
      - DB_PASSWORD=12345
      - DB_PORT=5432
    ports:
      - "8080:8080"

networks:
  remessaNetwork:
    driver: bridge