version: '3'

services:
  db:
    image: postgres:latest
    container_name: postgresDB
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: myDB
    ports:
      - "5432:5432"
