version: '3'

services:
  postgresDBWriter:
    image: postgres:latest
    container_name: postgresDBWriter
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    restart: always
    # networks: 
    #   - remessaNetwork

  rabbitmq:
    image: rabbitmq:3.12-management
    ports:
      - 5672:5672
      - 15672:15672

#   remittance-processor:
#     build: "./remessaAPI"
#     container_name: remessaApi
#     depends_on: 
#       - postgresDBWriter
#     networks:
#       - remessaNetwork
#     environment:
#       - PORT=8080
#       - DB_HOST=postgresDBWriter
#       - DB_NAME=postgres
#       - DB_USER=admin
#       - DB_PASSWORD=123456
#       - DB_PORT=5432
#     ports:
#       - "8080:8080"

#   cnab-remittance:



# networks:
#   remessaNetwork:
#     driver: bridge